package cosmoplas.reglas;

//from row number: 1
rule "Row 1 RuleFirma"
	dialect "mvel"
	when
		f1 : Firma( idBodega == 1 , idMovimiento == 1 , fechaMovimiento == fechaDespacho )
	then
		f1.setValidacion( true );
end

//from row number: 2
rule "Row 2 RuleFirma"
	dialect "mvel"
	when
		f1 : Firma( idBodega == 2 , idMovimiento == 1 , fechaMovimiento == fechaDespacho )
	then
		f1.setValidacion( false );
end
//from row number: 1
rule "Row 3 RuleFirma"
	dialect "mvel"
	when
		f1 : Firma( idBodega == 1 , idMovimiento == 1 , fechaMovimiento != fechaDespacho )
	then
		f1.setValidacion( false );
end